spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
      # http://localhost:8080/h2-console/
      console:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update

