/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core2_jni_windows_Win32RegKeyNameEnumeration */

#ifndef _Included_core2_jni_windows_Win32RegKeyNameEnumeration
#define _Included_core2_jni_windows_Win32RegKeyNameEnumeration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core2_jni_windows_Win32RegKeyNameEnumeration
 * Method:    nextElement
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_core2_jni_windows_Win32RegKeyNameEnumeration_nextElement
  (JNIEnv *, jobject);

/*
 * Class:     core2_jni_windows_Win32RegKeyNameEnumeration
 * Method:    hasMoreElements
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_core2_jni_windows_Win32RegKeyNameEnumeration_hasMoreElements
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
